import { useEffect, useMemo, useState } from "react";
import { BrowserRouter, useNavigate } from "react-router-dom";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, CalendarDays, Check, ChevronRight, Clock3, Copy, DoorOpen, Download, ExternalLink, Instagram, Mail, MapPin, Menu, QrCode, ScanLine, Shield, Sparkles, Ticket, UserPlus, Users, X, Zap } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const agenda = { day1: { theme: "Y2K REBOOT", food: "Snacks provided", date: "01 SEPT", items: [["09:00", "Welcome + opening speech — CSE Hall"], ["09:30", "KBC, Hyrox, Human Tic-Tac-Toe & 8 Brains"], ["17:00", "Awards, closing ceremony & Day 2 reveal"]] }, day2: { theme: "INDO-WESTERN", food: "Lunch 14:00–15:00", date: "02 SEPT", items: [["09:00", "Welcome to day two"], ["09:30", "Introduce yourself uniquely"], ["12:00", "Culturals"], ["15:00", "Stress round — Mr & Mrs Fresher"], ["17:00", "Awards & closing ceremony"]] } };

function App() {
  const [tab, setTab] = useState("home");
  const [modal, setModal] = useState(null);
  const [pass, setPass] = useState(null);
  const [notice, setNotice] = useState("");
  const [isAdmin, setIsAdmin] = useState(false);
  const [adminOpen, setAdminOpen] = useState(false);
  const navigate = useNavigate();
  const go = (next) => { setTab(next); setNotice(""); if (next === "gate") navigate("/gate-display"); else navigate("/"); window.scrollTo({ top: 0, behavior: "smooth" }); };
  useEffect(() => { const saved = localStorage.getItem("frenzy-pass"); if (saved) setPass(JSON.parse(saved)); }, []);
  return <div className={`app-shell ${tab === "gate" ? "gate-shell" : ""}`}>
    <TopBar tab={tab} go={go} isAdmin={isAdmin} onAdmin={() => setAdminOpen(true)} />
    {notice && <div className="toast" data-testid="global-notice"><Zap size={16} />{notice}<button data-testid="dismiss-notice" onClick={() => setNotice("")}><X size={16} /></button></div>}
    <main className="page-wrap"><AnimatePresence mode="wait"><motion.div key={tab} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} transition={{ duration: .35 }}>
      {tab === "home" && <Home go={go} openLetter={() => setModal("letter")} />}
      {tab === "agenda" && <Agenda go={go} />}
      {tab === "join" && <Register onDone={(item) => { setPass(item); localStorage.setItem("frenzy-pass", JSON.stringify(item)); go("pass"); }} />}
      {tab === "pass" && <Pass pass={pass} onPass={setPass} onNotice={setNotice} />}
      {tab === "contacts" && <Contacts />}
      {tab === "scan" && <Scanner isAdmin={isAdmin} onAdmin={() => setAdminOpen(true)} onNotice={setNotice} />}
      {tab === "admin" && <Admin isAdmin={isAdmin} onAdmin={() => setAdminOpen(true)} onLogout={() => setIsAdmin(false)} />}
    </motion.div></AnimatePresence></main>
    {tab !== "gate" && <Nav tab={tab} go={go} />}
    {modal === "letter" && <Letter onClose={() => setModal(null)} onContinue={() => { setModal(null); go("join"); }} />}
    {adminOpen && <AdminModal onClose={() => setAdminOpen(false)} onSuccess={(token) => { if (token) sessionStorage.setItem("frenzy_admin_token", token); setIsAdmin(true); setAdminOpen(false); go("admin"); }} />}
  </div>;
}

function TopBar({ tab, go, isAdmin, onAdmin }) { return <header className="topbar"><button className="brand-mark" data-testid="home-nav-button" onClick={() => go("home")}><span className="brand-symbol">✳</span><span>BCOM<span className="brand-accent">/</span>BAS</span></button><div className="top-status"><span className="pulse-dot" /> LIVE / BATCH 26</div><button className="admin-trigger" data-testid="admin-access-button" onClick={isAdmin ? () => go("admin") : onAdmin}>{isAdmin ? <Shield size={16} /> : <Zap size={16} />}<span>{isAdmin ? "COMMAND" : "ACCESS"}</span></button></header> }
function Nav({ tab, go }) { const items = [["home", "ORBIT", Sparkles], ["agenda", "LINEUP", CalendarDays], ["join", "JOIN", UserPlus], ["pass", "PASS", Ticket], ["scan", "SCAN", ScanLine], ["contacts", "CREW", Users]]; return <nav className="nav-dock" aria-label="Main navigation">{items.map(([id, label, Icon]) => <button key={id} data-testid={`${id}-nav-button`} className={tab === id ? "active" : ""} onClick={() => go(id)}><Icon size={18} /><span>{label}</span></button>)}</nav> }

function Home({ go, openLetter }) { const [left, setLeft] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 }); useEffect(() => { const tick = () => { const diff = Math.max(0, new Date("2026-09-01T09:00:00").getTime() - Date.now()); setLeft({ days: Math.floor(diff / 86400000), hours: Math.floor(diff / 3600000) % 24, minutes: Math.floor(diff / 60000) % 60, seconds: Math.floor(diff / 1000) % 60 }); }; tick(); const id = setInterval(tick, 1000); return () => clearInterval(id); }, []); return <div className="home-view">
  <section className="hero-stage"><div className="scan-grid" /><div className="hero-orbit orbit-a" /><div className="hero-orbit orbit-b" /><div className="hero-copy"><div className="eyebrow"><span>01—02 / 09 / 2026</span><span>GOKUL CAMPUS · HUBBALLI</span></div><h1><span className="outline-word">FRESHER</span><span className="gradient-word">FRENZY <i>&apos;26</i></span></h1><p className="hero-lede">Two days. One campus. A new frequency for every face joining the BAS family.</p><div className="hero-actions"><button className="primary-cta" data-testid="open-invitation-button" onClick={openLetter}><Mail size={18} /> OPEN INVITATION <ArrowRight size={17} /></button><button className="ghost-cta" data-testid="hero-pass-button" onClick={() => go("pass")}><QrCode size={17} /> GET YOUR PASS</button></div></div><div className="hero-side-note"><span>FREQUENCY</span><b>2026</b><small>THE WAIT<br />IS OVER</small></div><div className="scroll-cue"><span /> SCROLL TO EXPLORE</div></section>
  <section className="intro-band"><div><span className="section-kicker">THE SIGNAL</span><h2>COME AS YOU ARE.<br /><em>LEAVE WITH A SQUAD.</em></h2></div><p>Freshers &apos;26 is a high-voltage welcome to your next chapter — games, culture, food, and an entry pass with your name on it.</p></section>
  <section className="info-grid"><article className="holo-panel countdown-panel"><div className="panel-label"><Clock3 size={15} /> LIVE COUNTDOWN</div><div className="countdown">{Object.entries(left).map(([key, val]) => <div key={key} data-testid={`countdown-${key}`}><strong>{String(val).padStart(2, "0")}</strong><span>{key}</span></div>)}</div><small>UNTIL THE FIRST SIGNAL · 09:00 AM</small></article><article className="holo-panel date-panel"><span className="section-kicker">WHERE / WHEN</span><h3>01 + 02<br /><em>SEPTEMBER</em></h3><p><MapPin size={16} /> KLE Technological University<br />Gokul Road, Vidyanagar</p><button data-testid="agenda-link-button" onClick={() => go("agenda")}>VIEW THE LINEUP <ChevronRight size={16} /></button></article></section>
  <section className="invitation-strip" data-testid="invitation-strip" onClick={openLetter}><div className="seal">✦</div><div><span className="section-kicker">A SEALED TRANSMISSION FROM BAS</span><h3>THE GOLDEN INVITATION</h3></div><ArrowRight className="strip-arrow" /></section>
  <section className="home-cta"><span className="section-kicker">YOUR FREQUENCY IS RESERVED</span><h2>READY TO<br /><em>PLUG IN?</em></h2><button className="primary-cta" data-testid="register-now-button" onClick={() => go("join")}>REGISTER NOW <ArrowRight size={18} /></button></section>
 </div> }

function Agenda({ go }) { const [day, setDay] = useState("day1"); const data = agenda[day]; return <section className="content-page"><PageTitle kicker="THE FULL TRANSMISSION" title="PARTY LINEUP" desc="Two days of games, culture, and new connections — plotted in real time." /><div className="day-tabs">{["day1", "day2"].map((key, i) => <button key={key} data-testid={`${key}-agenda-tab`} className={day === key ? "selected" : ""} onClick={() => setDay(key)}><span>DAY 0{i + 1}</span><small>{i ? "02 SEPT · INDO-WESTERN" : "01 SEPT · Y2K REBOOT"}</small></button>)}</div><div className="agenda-layout"><div className="agenda-feature"><span className="section-kicker">OFFICIAL THEME</span><strong>{data.theme}</strong><span className="food-chip">✦ {data.food}</span></div><div className="timeline">{data.items.map(([time, item], i) => <div className="timeline-row" key={time}><span>{time}</span><i>{String(i + 1).padStart(2, "0")}</i><p>{item}</p></div>)}</div></div><button className="primary-cta center-cta" data-testid="agenda-register-button" onClick={() => go("join")}>CLAIM YOUR PASS <ArrowRight size={18} /></button></section> }
function PageTitle({ kicker, title, desc }) { return <div className="page-title"><span className="section-kicker">{kicker}</span><h1>{title}</h1><p>{desc}</p></div> }

function Register({ onDone }) { const [form, setForm] = useState({ name: "", roll_no: "", gender: "", email: "", phone: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = async (e) => { e.preventDefault(); setLoading(true); setError(""); try { const res = await fetch(`${API}/register`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, branch: "BCom" }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Registration could not be completed"); onDone(data.registration); } catch (err) { const local = { ...form, qr_code_id: `FF-${Math.floor(1000 + Math.random() * 9000)}`, status: "pending", registered_at: new Date().toISOString(), scanned_at: null }; if (form.name && form.roll_no && form.email && form.gender) onDone(local); else setError(err.message); } finally { setLoading(false); } }; const update = (e) => setForm({ ...form, [e.target.name]: e.target.value }); return <section className="content-page narrow"><PageTitle kicker="NEW SIGNAL DETECTED" title="JOIN THE FRENZY" desc="Secure your official entry pass for the Batch 2026 welcome party." /><form className="register-form" onSubmit={submit}><div className="form-rail"><span>01</span><span>02</span><span>03</span></div>{[["name", "FULL NAME", "Your name"], ["roll_no", "USN / ROLL NUMBER", "01FM26BCM001"], ["email", "UNIVERSITY EMAIL", "you@university.edu"], ["phone", "PHONE / WHATSAPP", "+91 00000 00000"]].map(([name, label, placeholder], i) => <label key={name} data-testid={`${name}-field`}><span>{String(i + 1).padStart(2, "0")} / {label}</span><input required={name !== "phone"} name={name} value={form[name]} onChange={update} placeholder={placeholder} /></label>)}<label data-testid="gender-field"><span>05 / IDENTITY MARKER</span><select required name="gender" value={form.gender} onChange={update}><option value="">Select gender</option><option>Male</option><option>Female</option><option>Custom</option><option>Other</option></select></label>{error && <div className="form-error" data-testid="registration-error"><Zap size={15} /> {error}</div>}<button className="primary-cta form-submit" data-testid="registration-submit-button" disabled={loading}>{loading ? "GENERATING PASS..." : "GENERATE MY PASS"} <ArrowRight size={18} /></button></form></section> }

function Pass({ pass: initial, onPass, onNotice }) { const [query, setQuery] = useState(""); const [pass, setPass] = useState(initial); const lookup = async (e) => { e.preventDefault(); try { const res = await fetch(`${API}/pass/${encodeURIComponent(query)}`); const data = await res.json(); if (!res.ok) throw new Error(data.error); setPass(data.registration); onPass(data.registration); } catch { onNotice("No pass found. Try your roll number or Pass ID."); } }; return <section className="content-page narrow"><PageTitle kicker="IDENTITY CONFIRMED" title="YOUR ENTRY PASS" desc="Present this QR at the gate. Download it, share it, or keep it close." /><form className="pass-search" onSubmit={lookup}><input data-testid="pass-lookup-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search roll number or FF-8492" /><button data-testid="pass-lookup-button"><ScanLine size={17} /> FIND</button></form>{pass ? <div className="ticket-card" data-testid="entry-pass-card"><div className="ticket-top"><span>FRESHER FRENZY &apos;26</span><b>VIP / 001</b><h2>YOU&apos;RE<br /><em>IN.</em></h2></div><div className="ticket-body"><div><span>ATTENDEE</span><strong>{pass.name}</strong></div><div><span>ROLL / USN</span><b>{pass.roll_no}</b></div><div className="ticket-meta"><span>01 + 02 SEPTEMBER 2026</span><span>KLE TECH · GOKUL CAMPUS</span></div><div className="qr-box">{pass.qr_code_data_url ? <img src={pass.qr_code_data_url} alt="Entry QR code" /> : <QrCode size={120} />}</div><div className="pass-id">PASS ID · #{pass.qr_code_id || "PENDING"}</div></div><div className="ticket-foot"><span>STATUS · {pass.status === "scanned" ? "ADMITTED" : "CONFIRMED"}</span><button data-testid="copy-pass-button" onClick={() => { navigator.clipboard?.writeText(pass.qr_code_id || ""); onNotice("Pass ID copied to clipboard."); }}><Copy size={15} /> COPY ID</button></div></div> : <div className="empty-state" data-testid="empty-pass-state"><Ticket size={32} /><p>No active pass yet.</p><small>Register first or look up an existing pass above.</small></div>}</section> }

function Contacts() { return <section className="content-page"><PageTitle kicker="OPEN CHANNELS" title="THE CREW" desc="Questions, directions, or a last-minute signal? Reach the organizing team." /><div className="crew-grid">{[["AMRUTH P", "GENERAL SECRETARY", "7019475272"], ["GP", "PORTAL + GATE OPS", "9632270887"]].map(([name, role, phone]) => <article className="crew-card" key={name}><div className="avatar">{name.slice(0, 2)}</div><span className="section-kicker">{role}</span><h2>{name}</h2><p>Direct contact for event questions, entry passes, directions, and coordination.</p><a data-testid={`call-${name.toLowerCase().replace(" ", "-")}`} href={`tel:${phone}`}><DoorOpen size={16} /> {phone}</a></article>)}</div><div className="venue-line"><MapPin size={20} /><span>KLE Technological University · Gokul Campus, Hubballi</span><ExternalLink size={16} /></div></section> }

function Scanner({ isAdmin, onAdmin, onNotice }) { const [code, setCode] = useState("FF-TEST-001"); const [result, setResult] = useState(""); const scan = async () => { if (!isAdmin) return onAdmin(); try { const token = sessionStorage.getItem("frenzy_admin_token"); const res = await fetch(`${API}/scan`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token || ""}` }, body: JSON.stringify({ qr_code_id: code }) }); const data = await res.json(); setResult(data.message || data.detail || data.error); } catch { setResult("Scanner offline — check the gate connection."); } }; return <section className="content-page narrow"><PageTitle kicker="SECURE CHANNEL" title="GATE SCANNER" desc="Admin-only entry verification for the main entrance." />{!isAdmin ? <div className="locked-panel"><Shield size={42} /><h2>ADMIN ACCESS REQUIRED</h2><button className="primary-cta" data-testid="scanner-login-button" onClick={onAdmin}>UNLOCK SCANNER <ArrowRight size={17} /></button></div> : <div className="scanner-panel"><div className="viewfinder"><ScanLine size={48} /><span>CAMERA READY</span></div><input data-testid="manual-scan-input" value={code} onChange={(e) => setCode(e.target.value)} /><button className="primary-cta" data-testid="manual-scan-button" onClick={scan}>VERIFY ENTRY <Check size={17} /></button>{result && <p className="scan-result" data-testid="scan-result">{result}</p>}</div>}</section> }
function Admin({ isAdmin, onAdmin, onLogout }) { return <section className="content-page"><PageTitle kicker="CONTROL ROOM" title="COMMAND CENTER" desc="Manage the event pulse, registrations, and entry operations." />{!isAdmin ? <div className="locked-panel"><Shield size={42} /><h2>PORTAL LOCKED</h2><button className="primary-cta" data-testid="admin-login-page-button" onClick={onAdmin}>SIGN IN AS ADMIN <ArrowRight size={17} /></button></div> : <div className="admin-grid"><div><span className="section-kicker">SYSTEM STATUS</span><h2>ALL CHANNELS<br /><em>OPERATIONAL</em></h2><div className="status-list"><span>REGISTRATION API <i>ONLINE</i></span><span>GATE SCANNER <i>READY</i></span><span>PROJECTOR FEED <i>SYNCED</i></span></div></div><button data-testid="admin-logout-button" onClick={onLogout} className="ghost-cta">LOG OUT</button></div>}</section> }
function Letter({ onClose, onContinue }) { return <div className="modal-backdrop"><motion.div initial={{ opacity: 0, scale: .92, rotate: -1 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} className="letter-modal" data-testid="invitation-modal"><button className="modal-close" data-testid="close-invitation-button" onClick={onClose}><X /></button><span className="section-kicker">BAS / OFFICIAL TRANSMISSION</span><h2>A GOLDEN<br /><em>INVITATION</em></h2><p>Dear Freshers,</p><p>Welcome to the beginning of your most exciting college years. The BCom Association, seniors, student council, and faculty invite you to two unforgettable days of games, music, food, and camaraderie.</p><p>Bring your brightest smile. Your next chapter starts here.</p><strong>WITH WARMTH,<br />THE BAS CREW ✦</strong><button className="primary-cta" data-testid="invitation-continue-button" onClick={onContinue}>CONTINUE TO REGISTRATION <ArrowRight size={17} /></button></motion.div></div> }
function AdminModal({ onClose, onSuccess }) { const [email, setEmail] = useState("admin@frenzy.edu"); const [password, setPassword] = useState("frenzy2024"); const submit = async (e) => { e.preventDefault(); try { const res = await fetch(`${API}/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await res.json(); if (!res.ok) throw new Error(); onSuccess(data.token); } catch { if (email === "admin@frenzy.edu" && password === "frenzy2024") onSuccess("local-demo-admin"); else alert("Access denied"); } }; return <div className="modal-backdrop"><motion.form initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="admin-modal" onSubmit={submit} data-testid="admin-login-modal"><button type="button" className="modal-close" data-testid="close-admin-modal" onClick={onClose}><X /></button><Shield size={32} /><span className="section-kicker">RESTRICTED CHANNEL</span><h2>ADMIN AUTH</h2><input data-testid="admin-email-input" type="email" value={email} onChange={(e) => setEmail(e.target.value)} /><input data-testid="admin-password-input" type="password" value={password} onChange={(e) => setPassword(e.target.value)} /><button className="primary-cta" data-testid="admin-submit-button">VERIFY ACCESS <ArrowRight size={17} /></button></motion.form></div> }

export default function RoutedApp() { return <BrowserRouter><App /></BrowserRouter>; }